name: Build & Push

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/pteromyini123
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Read VERSION
        id: read-version
        run: echo "TAG=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Dummy tests
        run: |
          echo "Placeholder tests passed"

      - name: Log-in to GHCR (via built-in token)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set-up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push service1
        uses: docker/build-push-action@v5
        with:
          context: ./services/service1
          push: true
          visibility: public
          tags: |
            ${{ env.REGISTRY }}/service1:${{ steps.read-version.outputs.TAG }}
            ${{ env.REGISTRY }}/service1:latest


      - name: Build & push service2
        uses: docker/build-push-action@v5
        with:
          context: ./services/service2
          push: true
          visibility: public
          tags: |
            ${{ env.REGISTRY }}/service2:${{ steps.read-version.outputs.TAG }}
            ${{ env.REGISTRY }}/service2:latest
